services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./node-server:/app
    ports:
      - "3000:3000"
    env_file:
      - .env

  python-server:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./python-server:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
