# Dockerfile.python
FROM python:3.10-slim

WORKDIR /app
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY python-server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY python-server/ ./

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
