version: "3.9"
services:
  mcp:
    build: ./mcp                # Dockerfile.python を mcp/ に置く
    ports: ["8000:8000"]
    env_file:
      - mcp/.env
    volumes:
      - ./mcp:/app              # 開発時ホットリロード
  redis:
    image: redis:7
    ports: ["6379:6379"]
# node-server が不要なら以下を削除
#  legacy-api:
#    build: ./node-server
#    ports: ["3000:3000"]

